// src/components/react/Counter.tsx
import { useState } from "react";

type Props = {
  defaultCount?: number;
};

export const Counter: React.FC<Props> = ({ defaultCount = 10 }) => {
  const [count, setCount] = useState(defaultCount);

  return (
    <>
      <button onClick={() => setCount((v) => v + 1)}>
        {`Count: ${count}`}
      </button>
    </>
  );
};

// src/components/vue/Counter.vue
<script setup lang="ts">
import { ref } from "vue";

const { defaultCount = 0 } = defineProps<{ defaultCount?: number }>();
const count = ref(defaultCount);
const increment = () => (count.value += 1);
</script>

<template>
  <button @click="increment">
    <span>Count: {{ count }}</span>
  </button>
</template>
